コードのコピー機能を追加
aws-samples/bedrock-claude-chat pull request #129
Opened 2024-03-06 06:06 UTC by kyosuke-kobayashi-lvgs

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-06 06:19 UTC, kyosuke-kobayashi-lvgs commented
@wadabee 
FE側の実装行いました
レビューお願いします！

2024-03-07 02:24 UTC, wadabee requested changes
PRありがとうございます！
コメントを記載しているので、ご対応をお願いします。

2024-03-07 02:24 UTC, wadabee commented on frontend/src/components/Markdown.tsx
> +
既に`frontend/src/components/ButtonCopy.tsx`というコンポーネントがあるので、コードや挙動の統一という観点で、こちらのコンポーネントを利用するように修正をお願いします。

2024-03-07 03:34 UTC, kyosuke-kobayashi-lvgs commented on frontend/src/components/Markdown.tsx
> +
こちら、修正いたしました！

2024-03-07 03:34 UTC, kyosuke-kobayashi-lvgs commented on frontend/src/components/Markdown.tsx
> +
@wadabee

2024-03-07 04:23 UTC, wadabee approved these changes
LGTM !!
コントリビューションありがとうございます！

2024-03-07 04:23 UTC, merged