会話履歴にローディングを追加
aws-samples/bedrock-claude-chat pull request #130
Opened 2024-03-06 06:54 UTC by kyosuke-kobayashi-lvgs

*Issue #, if available:*
https://github.com/aws-samples/bedrock-claude-chat/issues/17
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-06 06:55 UTC, kyosuke-kobayashi-lvgs commented
@statefb 
ISSUE　対応しました！

2024-03-07 02:59 UTC, wadabee requested changes
PRありがとうございます！
コメントを記載したので、ご対応をよろしくお願いいたします。

2024-03-07 02:59 UTC, wadabee commented on frontend/src/components/ChatListDrawer.tsx
> +                  <Spinner />
本アセットのアイコンは、統一感を出す目的で可能な限り [Phosphor Icons](https://phosphoricons.com/)を利用するようにしています。
こちらのアイコンを利用するように、修正をお願いします。`circle-notch`が実装いただいたものに近いかと思います。
react-iconsというライブラリから利用しているので、以下のようにImport可能です。
```
import { PiCircleNotch } from "react-icons/pi";
```

2024-03-07 03:39 UTC, kyosuke-kobayashi-lvgs commented on frontend/src/components/ChatListDrawer.tsx
> +                  <Spinner />
こちら修正しました！

2024-03-07 03:39 UTC, kyosuke-kobayashi-lvgs commented on frontend/src/components/ChatListDrawer.tsx
> +                  <Spinner />
@wadabee

2024-03-07 04:20 UTC, wadabee approved these changes
LGTM !!
コントリビューションありがとうございます！

2024-03-07 04:20 UTC, merged