Add: Prompt library link
aws-samples/bedrock-claude-chat pull request #136
Opened 2024-03-07 07:24 UTC by statefb

*Issue #, if available:*

*Description of changes:*
Add [prompt library link](https://docs.anthropic.com/claude/prompt-library) to samples
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/23316627/5cd1dfce-b452-4298-91e6-1ba2a6d84735)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-08 02:04 UTC, wadabee requested changes
ありがとうございます！
コメントの対応をお願いしますmm

2024-03-08 02:04 UTC, wadabee commented on frontend/src/components/DialogInstructionsSamples.tsx
> +            href="https://docs.anthropic.com/claude/prompt-library"
今回のケースは当てはまりませんが、言語によってURLが異なることもあるので、URLもi18n対応をお願いしますmm

2024-03-08 02:04 UTC, wadabee commented on frontend/src/components/DialogInstructionsSamples.tsx
> +            className="text-blue-600 hover:text-blue-800">
actionableなコンポーネントは、`aws-sea-blue`のカラーを利用しているのでそちらの利用をお願いします。
`underline`を設定すれば、押せる感も出せると思います。

2024-03-08 04:26 UTC, statefb commented on frontend/src/components/DialogInstructionsSamples.tsx
> +            className="text-blue-600 hover:text-blue-800">
対応しました！

2024-03-08 04:27 UTC, statefb commented on frontend/src/components/DialogInstructionsSamples.tsx
> +            href="https://docs.anthropic.com/claude/prompt-library"
ブラウザ側で自動的に判別してくれるようなので、不要かと思い、特に設定していません。

2024-03-08 09:10 UTC, wadabee commented on frontend/src/components/DialogInstructionsSamples.tsx
> +            href="https://docs.anthropic.com/claude/prompt-library"
べき論的な話ですみませんmm
今回のケースは対応しなくても動くのですが、i18n対応しているアセットなので、本来i18nで管理すべき部分はそちらで管理しておきたいという意図になります！

2024-03-08 10:15 UTC, statefb commented on frontend/src/components/DialogInstructionsSamples.tsx
> +            href="https://docs.anthropic.com/claude/prompt-library"
なるほど、意図を理解しました！commitしたのでご確認お願いします！

2024-03-11 00:24 UTC, wadabee approved these changes
LGTM!
ありがとうございました！

2024-03-11 00:24 UTC, merged