[Feature Request]LLM parameter setting from Frontend
aws-samples/bedrock-claude-chat pull request #188
Opened 2024-03-25 12:45 UTC by 2814109

…ents.

*Issue #, if available:*
https://github.com/aws-samples/bedrock-claude-chat/issues/166
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-25 13:52 UTC, 2814109 commented on backend/app/repositories/models/custom_bot.py
> +class ChunkParamsModel(BaseModel):
[memo]
ChunkParamsとして定義するのではなく、KnowledgeModelの一部として定義した方が良いかも

2024-03-28 00:12 UTC, statefb commented on backend/app/repositories/models/custom_bot.py
> +class ChunkParamsModel(BaseModel):
Embedding taskの設定はひとまず全部突っ込めるようにしたいので、EmbeddingParamsなどより上位の概念の名前にしてください！（今後チャンキング以外のパラメータが設定可能になる可能性もあるため）

2024-03-28 03:22 UTC, 2814109 commented on backend/app/repositories/models/custom_bot.py
> +class ChunkParamsModel(BaseModel):
ご指摘ありがとうございます！
リネームしました！

引き続き実装進めていきますmm

2024-03-28 03:29 UTC, 2814109 commented
memo
mypyエラーとformatエラー修正

2024-03-29 07:26 UTC, kyosuke-kobayashi-lvgs commented on backend/app/usecases/bot.py
> +        and bot_input.embedding_params
rm

2024-03-29 07:26 UTC, kyosuke-kobayashi-lvgs commented on backend/app/repositories/custom_bot.py
> +            UpdateExpression="SET Title = :title, Description = :description, Instruction = :instruction,EmbeddingParams = embedding_params, Knowledge = :knowledge, SyncStatus = :sync_status, SyncSta
add :

2024-03-29 07:27 UTC, kyosuke-kobayashi-lvgs commented on backend/app/usecases/bot.py
> +                chunk_size=bot_input.chunk_size, chunk_overlap=bot_input.chunk_overlap
correct 
```
bot_input.embedding_params.chunk_size
```

2024-04-01 07:56 UTC, kyosuke-kobayashi-lvgs commented on backend/app/repositories/custom_bot.py
> +        embedding_params=EmbeddingParamsModel(**item["EmbeddingPrams"]),
typo Params

2024-04-01 08:00 UTC, kyosuke-kobayashi-lvgs commented on backend/tests/repositories/test_conversation.py
>  from app.repositories.conversation import (
move here
```
from app.config import EMBEDDING_CONFIG
```

2024-04-01 08:02 UTC, kyosuke-kobayashi-lvgs commented on backend/tests/repositories/test_custom_bot.py
L583
test_update_bot_visibility

add
```
            embedding_params=EmbeddingParamsModel(
                chunk_size=EMBEDDING_CONFIG["chunk_size"],
                chunk_overlap=EMBEDDING_CONFIG["chunk_overlap"],
            ),
```

2024-04-02 02:47 UTC, kyosuke-kobayashi-lvgs commented on backend/tests/usecases/test_bot.py
> +from app.tests.utils.optimized import (
ModuleNotFoundError

2024-04-02 07:13 UTC, kyosuke-kobayashi-lvgs commented on backend/tests/usecases/test_bot.py
> +from app.tests.utils.optimized import (
tests => tests_dev Successs

2024-04-02 07:42 UTC, kyosuke-kobayashi-lvgs commented on backend/tests/usecases/test_bot.py
> +from app.tests.utils.optimized import (
FYI : 
```python
sys.path.insert(0, ".")
```

2024-04-03 02:03 UTC, kyosuke-kobayashi-lvgs commented
Prefix existing test scripts with test.

2024-04-03 05:33 UTC, kyosuke-kobayashi-lvgs commented
update readme
```
## Unit test

```sh
python tests/test_bedrock.py
python tests/test_repositories/test_conversation.py
python tests/test_repositories/test_custom_bot.py
python tests/test_usecases/test_bot.py
python tests/test_usecases/test_chat.py
``````

2024-04-03 11:34 UTC, 2814109 commented
format修正

2024-04-04 04:31 UTC, statefb commented on backend/app/usecases/bot.py
> +        else EMBEDDING_CONFIG["chunk_size"]
ここだけではなく全体に通じて言えることですが、EMBEDDING_CONFIGはデフォルト値として扱われているので、DEFAULT_EMBEDDING_CONFIGに名称変更いただけませんか？

2024-04-04 04:31 UTC, statefb commented on backend/embedding/main.py
> +    chunk_size: int = EMBEDDING_CONFIG["chunk_size"],
デフォルト引数を設定されていますが、bot create時にデフォルト値が作成されることが保証されているので、これはなくても良いかと思いました！

2024-04-04 04:31 UTC, statefb commented on backend/tests/test_usecases/utils/optimized.py
> +def create_private_bot(
テスト用途であることを明示するため、create_test_private_botなどの名前に変更ください！

2024-04-04 04:31 UTC, statefb commented on backend/tests/test_usecases/utils/optimized.py
> +def create_public_bot(
こちらも同様、テスト用であることをわかるようにしてください！

2024-04-04 04:31 UTC, statefb commented on backend/tests/test_usecases/utils/optimized.py
ファイル名がoptimizedだとわかりにくいので、bot_fixture, bot_factoryなどの名前に変更いただけませんか？

2024-04-04 04:31 UTC, statefb commented on frontend/src/pages/BotEditPage.tsx
> +  const [embeddingParams, dispath] = useReducer(embeddingParamsReducer, {
このアプリは状態管理にZustandを利用しています。プロジェクト全体でzustandで検索かけるといくつかコンポーネントがヒットするので、Zustand利用する実装としてください！

2024-04-04 04:31 UTC, statefb commented on frontend/src/pages/BotEditPage.tsx
> +                    range={{
chunkサイズやオーバーラップをスライダーとして実装されたのには何か理由がありますか？確かに技術的な上限や下限は存在しますが、素直にnumberのみ許容するテキストボックスでも良いかなと思いました（これは@wadabeeさんの意見も聞いてみたいところです）

2024-04-04 04:34 UTC, statefb commented on frontend/src/pages/BotEditPage.tsx
> +  const [embeddingParams, dispath] = useReducer(embeddingParamsReducer, {
（今回の実装の場合、そこまで複雑ではないのでuseStateでも十分かと思いました）

2024-04-04 04:36 UTC, statefb commented
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/23316627/6dc2e232-7379-423a-a2a1-758cb4c2b430)

2024-04-04 04:45 UTC, 2814109 commented on frontend/src/pages/BotEditPage.tsx
> +                    range={{
@statefb 
コメントありがとうございます！
こちら、迷ったのですが２つの観点でスライダーにしました
観点１：闇雲に極端に大きい値にすると、せっかく設定できても意味をなさないようなアウトプットになってしまうかなと思ったので、現実的に利用しやすい・意味のある量になる境界値をシステム側で制御してあげるのがユーザーフレンドリーなのかなと思った次第でした
ただ、境界値としてどこまでが妥当なのかといった部分に明確な判断基準がなく、雰囲気で定義してしまっているのが正直なところでして、この辺りは相談させていただけると嬉しいですmm

観点２：テキストボックスの場合、UIとして空白部分が目立つ(イメージ、添付の画像のようになると思います）ので、スライダーとすることで画面上のバランスがいい（空白部分が減る）かなと思いました
<img width="882" alt="スクリーンショット 2024-04-04 13 41 17" src="https://github.com/aws-samples/bedrock-claude-chat/assets/49641703/19c692f2-05c3-476a-bf17-ee1b0db31c9f">

@wadabee 
UI部分、ご意見いただけると幸いですmm

2024-04-04 04:46 UTC, 2814109 commented on frontend/src/pages/BotEditPage.tsx
> +  const [embeddingParams, dispath] = useReducer(embeddingParamsReducer, {
承知しました！
他のパラメータとも合わせるといった観点でuseStateにしようと思いますmm

2024-04-04 04:52 UTC, statefb commented on backend/app/routes/schemas/bot.py
> +class EmbeddingParams(BaseSchema):
オーバーラップはチャンクサイズを超えることはないので、バリデータを設けても良いかと思いました。routes/schemas/api_publicationのPublishedApiThrottleクラスなどが参考になるかと思います。

2024-04-04 05:01 UTC, statefb commented on backend/app/routes/schemas/bot.py
> +class EmbeddingParams(BaseSchema):
（理想的にはFE・BE共にバリデータが実装されている状態がもちろん望ましいです）

2024-04-04 05:22 UTC, statefb commented on frontend/src/pages/BotEditPage.tsx
> +                    range={{
なるほどです、確かにそうですね！技術的にはcohere multilingualやclaudeが受け付けるトークン量に依存しますが、これは他のパラメータ（たとえば何個分のチャンクをRAGデータソースとして利用するか等）にも依存するので、いかなるケースにおいてもエラーが発生しない、かつ妥当な値のレンジを定義するのは大変かと思います。

一つの目安ですが、Claude3が最大200,000 ([source](https://aws.amazon.com/jp/about-aws/whats-new/2024/03/anthropics-claude-3-sonnet-model-amazon-bedrock/)), corere multilingual v3が512 ([source](https://docs.cohere.com/docs/embed-2))とあるので、チャンクサイズの最大値は512とし、オーバーラップは安全のためのバッファを設けて半分の256が良いかと思っています

2024-04-04 05:25 UTC, 2814109 commented on frontend/src/pages/BotEditPage.tsx
> +                    range={{
コメントありがとうございます！

上記参考にさせていただき、実装修正しますmm

2024-04-04 05:55 UTC, 2814109 commented on backend/tests/test_usecases/utils/optimized.py
> +def create_private_bot(
create_bot_alias
こちらも水平展開して修正しておきます！

create_test_bot_alias

2024-04-04 05:56 UTC, 2814109 commented on backend/tests/test_usecases/utils/optimized.py
> +def create_private_bot(
create_test_instruction_template
こちらも同上です！

2024-04-05 02:21 UTC, wadabee commented on frontend/src/pages/BotEditPage.tsx
> +                    range={{
上限、下限のあるRangeの入力については、Sliderがよくある入力方法かなと思います！（バリデーションする必要もないですし）
自分の設定値がどの辺に位置しているのかというのが視覚的にわかるのも、Sliderの良いポイントですね
ただ、「1024」などJustで値を設定したい場合に、操作性が良くないのでテキストで補助入力できる欄は必須かなと思います（マネコンのBedrockのPlaygroundのようなイメージ）

2024-04-05 03:06 UTC, 2814109 commented on frontend/src/pages/BotEditPage.tsx
> +                    range={{
@wadabee 
ご指摘ありがとうございます！
テキストで補助入力の点、確かにおっしゃる通りだと思いました！

inputも追加してみますmm

2024-04-08 03:05 UTC, wadabee commented on frontend/src/components/Slider.tsx
> +        />
数値入力のINPUTは、`InputText.tsx`と同じスタイリングでお願いします（枠線、余白など）
または、幅の設定は`px`指定ではなく、tailwindのプリセットを使うようにお願いします。

2024-04-08 03:05 UTC, wadabee commented on frontend/src/components/Slider.tsx
> +export const Slider: FC<Props> = (props) => {
また、RangeとTextは横並びになるように配置をお願いします。
赤枠部分の余白を無くしたいという意図です。
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/52243855/4877f2bd-e658-4dac-8069-76872569c90e)

2024-04-08 04:28 UTC, 2814109 commented on frontend/src/components/Slider.tsx
> +export const Slider: FC<Props> = (props) => {
@wadabee 
こちら、修正しました！

2024-04-08 04:33 UTC, 2814109 commented on frontend/src/components/Slider.tsx
> +        />
こちら、修正しました！
text-centerだけ、InputTextと違うのですが、もし不要であれば削除しますmm

2024-04-09 01:28 UTC, 2814109 commented
@wadabee 
テスト全て通りました！
お手数ですが再度レビューお願いしますmm

2024-04-09 11:32 UTC, wadabee requested changes
細かい指摘が多くて恐縮ですが、修正をお願いします。

2024-04-10 04:43 UTC, 2814109 commented on frontend/src/i18n/ja/index.ts
> +        hint: '文書を一定のサイズの小さな部分に分割する際のサイズを指します。',
<img width="999" alt="スクリーンショット 2024-04-10 13 43 38" src="https://github.com/aws-samples/bedrock-claude-chat/assets/49641703/85f32db1-4b58-40e7-88fc-ab6d3d5faf8f">

添付画像のような感じで実装してみました！

2024-04-10 04:55 UTC, 2814109 commented on frontend/src/pages/BotEditPage.tsx
> +      /Got a larger chunk overlap \(\d+\) than chunk size \(\d+\), should be smaller\./;
こちら、読み込ませているデータの内容が因子になっているよう(分割規則の改行などが多い文章の場合に発生することまでわかってます)で、値で定義して回避することが難しいかなという認識でしたmm

2024-04-10 05:09 UTC, 2814109 commented on frontend/src/pages/BotEditPage.tsx
>                        <div className="rounded border bg-light-gray p-2 text-dark-gray">
<img width="912" alt="スクリーンショット 2024-04-10 14 09 00" src="https://github.com/aws-samples/bedrock-claude-chat/assets/49641703/74cb58f7-fe42-4a4c-9da5-d63f8043227d">

上記修正し、添付画像のようなエラー画面となりましたので、報告です！

2024-04-11 01:37 UTC, wadabee commented on frontend/src/i18n/ja/index.ts
> +        hint: '文書を一定のサイズの小さな部分に分割する際のサイズを指します。',
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/52243855/3d49a3fd-1a7d-44be-bd29-a860a143cfc3)
こちらのように各項目のラベルの隣に配置をお願いします！

2024-04-11 01:39 UTC, wadabee commented on frontend/src/pages/BotEditPage.tsx
> +  const validationCheck = useCallback((): boolean => {
`isValid`の場合は正常で`true`を返すように修正をお願いしますmm

2024-04-11 01:43 UTC, 2814109 commented on frontend/src/i18n/ja/index.ts
> +        hint: '文書を一定のサイズの小さな部分に分割する際のサイズを指します。',
すいません、こちらは、同一文言（以下）を二箇所に配置する認識であってますでしょうかmm
```
チャンクサイズが小さすぎると文脈情報が失われ、大きすぎると同一チャンクの中に異なる文脈の情報が存在することになり、検索精度が低下する場合があります。
```

2024-04-11 01:45 UTC, 2814109 commented on frontend/src/pages/BotEditPage.tsx
> +  const validationCheck = useCallback((): boolean => {
こちら修正しました！

2024-04-11 02:05 UTC, 2814109 commented on frontend/src/i18n/ja/index.ts
> +        hint: '隣接するチャンク間で共有される文字数を指します。',
すいません、２項目対応できてませんでしたmm

2024-04-11 02:05 UTC, 2814109 commented on frontend/src/i18n/ja/index.ts
> +        hint: '文書を一定のサイズの小さな部分に分割する際のサイズを指します。',
@wadabee 
上記認識間違ってました
chunkSizeとchunkOverlapのそれぞれについてhelp text を追加する対応で完了しましたmm

2024-04-11 06:57 UTC, wadabee approved these changes
LGTM!!

2024-04-11 06:58 UTC, merged