update to ^9.0.0 react-markdown
aws-samples/bedrock-claude-chat pull request #262
Opened 2024-04-19 04:30 UTC by Taikono-Himazin

*Issue #, if available:*

*Description of changes:*

#261 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-04-19 18:58 UTC, Taikono-Himazin commented
Memo TODO

I need to implement a copy button for the code, and a reference link for the documentation.

2024-04-21 11:09 UTC, Taikono-Himazin commented
@statefb 
review please

2024-04-23 02:54 UTC, wadabee requested changes
PRありがとうございます！
コメントを記載したので、ご確認をお願いします。

2024-04-23 02:54 UTC, wadabee commented on frontend/src/components/ChatMessageMarkdown.tsx
> -              />
好みの問題もありますが、修正前はVSCode風のスタイリングがされていてより見やすいと感じます。
今回導入いただいた、rehypeHilightも同様のスタイリングを適用することはできないでしょうか？

・修正前
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/52243855/2826448f-e22f-4355-ab86-e72a2ef15d09)
・修正後
<img width="478" alt="image" src="https://github.com/aws-samples/bedrock-claude-chat/assets/52243855/88c95927-07c4-4424-8776-5da23fd1eef7">

2024-04-23 02:54 UTC, wadabee commented on frontend/src/components/ChatMessageMarkdown.tsx
> +                  if (child?.props['data-footnote-ref']) {
ファイルやURLの設定されているボットに質問をすると参照情報を出力しますが、そちらが出力されなくなっています。
以下の画像の[1]のようなものです。
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/52243855/eeb84b3c-b8fd-478b-8d05-30a25b96acd8)

2024-04-23 23:26 UTC, Taikono-Himazin commented on frontend/src/components/ChatMessageMarkdown.tsx
> -              />
ほんとだ・・・なぜ気がつかなかったのか不思議です・・・。
ベースとなっているhighlight.jsにvscode風の味付けがなかったのでvs2015というthemeにしようと思います。

シンタックスハイライトですが、なぜかPythonとかjavascriptとかの自動検出が効かないので、対応苦戦中です。

2024-04-23 23:27 UTC, Taikono-Himazin commented on frontend/src/components/ChatMessageMarkdown.tsx
> +                  if (child?.props['data-footnote-ref']) {
この参照情報の出力ってどういう構造で行われているかのREADMEとかあったりしますか？
ちょっと構造がよく分からなくて

2024-04-24 14:25 UTC, wadabee commented on frontend/src/components/ChatMessageMarkdown.tsx
> +                  if (child?.props['data-footnote-ref']) {
Markdownコンポーネントをハックする形で実装しているので、分かりづらいですよね。。

まず、こちらの参照情報のリンクについては、MarkdownのFootnoteの書式を使って出力しています。
デフォルトのFootnoteの挙動は、脚注リンク（[1]と表示されているリンク）にアンカーリンクが設定され、参照リンク（文末に出てくる参照ドキュメントのリンク）にはドキュメントのリンクが設定されます。
以下のようなイメージです。
https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/

今回は、「脚注リンクをクリックすると、RAGに使用したドキュメントチャンクをポップアップ表示する」という挙動を実装したかったので、このFootnoteの出力を上書きして（HTMLを書き換えて）こちらを実現しました。
脚注リンクは、`data-footnote-ref`属性の設定された`sup`タグとして出力されるため、そちらを上書きして`RelatedDocumentLink`コンポーネントを設定しています。
参照リンクは、`data-footnotes`属性の設定された`selection`タグとして出力されるため、そちらを上書きして`null`を設定しています（今回は参照ドキュメントを出力しない）。

このFootnoteを出力するためには、回答の文末に`[^1]`というような参照情報を付与する必要がありますが、そちらはLLMに出力してもらうようにプロンプトで指示しています。
参照リンクは今回利用しないので不要なのですが、MarkdownコンポーネントにFootnoteとして処理してもらう必要があるので`[^1]: dummy`というようにダミーの文字列を出力しています（上記の`null`に置き換えられるので、ダミーは出力されない）

なぜこのようなトリッキーな実装をしたのかというと、以下の理由からです。
- 本来、プラグインとして実装すべきであるが、実装コスト的に見送った
- Markdown コンポーネントの利用をやめて独自実装する方法もあるが、プラグインの実装以上に非現実的

2024-04-24 15:57 UTC, Taikono-Himazin commented on frontend/src/components/ChatMessageMarkdown.tsx
> +                  if (child?.props['data-footnote-ref']) {
詳細な解説ありがとうございます。

申し訳ないのですが、上にも書きましたが別のところでメモリ負荷の問題が噴出して、react-markdownのバージョン変更を取りやめました。
ので、この問題もなくなっていると思います
よろしくお願いします。

2024-04-25 09:52 UTC, wadabee approved these changes
LGTM!!
ありがとうございます！

2024-04-25 09:52 UTC, merged