Feature: make display chunks swithable
aws-samples/bedrock-claude-chat pull request #298
Opened 2024-05-07 11:53 UTC by statefb

*Issue #, if available:*
Closes #248 

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-05-07 11:54 UTC, statefb commented
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/23316627/b02c3efa-49df-401b-9955-7c5c21c2786f)

2024-05-23 05:24 UTC, wadabee requested changes

2024-05-23 05:24 UTC, wadabee commented on frontend/src/i18n/ja/index.ts
> +            'ユーザーの質問に答えるために取得したコンテキストを引用するかどうかを設定します。有効にすると、ユーザーは元のソースURLやファイルにアクセスできます。',
ON/OFF関係なくドキュメントを参考に回答を生成するので、「引用するかどうか」だと誤解を招きそうな表現です。
「引用情報として表示するかどうか」だといかがでしょうか？

2024-05-23 05:24 UTC, wadabee commented on backend/app/routes/conversation.py
> +    response_model=list[RelatedDocumentsOutput] | None,
レスポンスについて、フロントエンド側の型情報も修正をお願いします！

2024-05-23 05:24 UTC, wadabee commented on frontend/src/pages/BotEditPage.tsx
> +                </div>
スイッチが下にはみ出していて収まりが悪いので、以下のように修正をお願いしますmm

![image](https://github.com/aws-samples/bedrock-claude-chat/assets/52243855/ecd38d4d-3570-48ee-8c26-44c5e5b3966d)

2024-05-27 08:16 UTC, wadabee approved these changes
LGTM!

2024-05-27 08:16 UTC, merged