fix css
aws-samples/bedrock-claude-chat pull request #358
Opened 2024-06-11 06:06 UTC by k70suK3-k06a7ash1

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-11 06:14 UTC, k70suK3-k06a7ash1 commented
ScrollToButtom

2024-06-13 01:28 UTC, k70suK3-k06a7ash1 commented
@wadabee 
フロントエンド側のスタイル修正しましたのでお手隙でご確認いただけますと幸いですmm

2024-06-13 04:47 UTC, wadabee requested changes
ご対応ありがとうございます！
1点気になる部分があるので、ご確認をお願いします。

2024-06-13 04:47 UTC, wadabee commented on frontend/src/pages/ChatPage.tsx
> +      onDragEnd={endDnd}>
スクロールバーが二重表示されているのが気になります。
ヘッダ、メッセージ、入力欄を一つのブロックに入れて、`flex-col`で縦方向に並べる形だといかがでしょうか？
ヘッダブロックを`sticky`、メッセージブロックを`h-full` にすれば、いい感じに表示されそうな気がします。
`InputChatContent.tsx`の中に余白の指定がありますが、もし邪魔だったら消してください！

2024-06-13 04:50 UTC, k70suK3-k06a7ash1 commented on frontend/src/pages/ChatPage.tsx
> +      onDragEnd={endDnd}>
レビューありがとうございます！！
修正します！

2024-06-13 05:15 UTC, k70suK3-k06a7ash1 commented
@wadabee 
修正しました！
レビュー指摘大変感謝ですmm

2024-06-13 05:17 UTC, k70suK3-k06a7ash1 commented
一応、今回の修正でuseLayoutEffectを使ってbottomまで移動しているので、ファーストビューで一番下のメッセージが表示される対応も入れております
ChatGPT側に準じて実装しました！

2024-06-13 05:40 UTC, wadabee approved these changes
LGTM!

2024-06-13 05:40 UTC, merged

2024-06-13 05:41 UTC, wadabee commented
ご対応ありがとうございました！
非常に見やすくなりました！