add keyboard command and fix bug
aws-samples/bedrock-claude-chat pull request #369
Opened 2024-06-14 01:47 UTC by k70suK3-k06a7ash1

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-14 01:47 UTC, k70suK3-k06a7ash1 commented on frontend/src/pages/ChatPage.tsx
> +            {bot?.conversationQuickStarters?.map((qs, idx) => (
add optional chain

2024-06-17 01:50 UTC, k70suK3-k06a7ash1 commented
チャット欄フォーカス
QuestionIconでショートカット一覧を表示

2024-06-17 03:48 UTC, k70suK3-k06a7ash1 commented
refをChatInput内で定義しているため、liftupするか、ref合成の必要ありそう？

2024-06-17 05:41 UTC, k70suK3-k06a7ash1 commented
綺麗ではないけどText Areaに個別にEffect追加

2024-06-17 06:01 UTC, k70suK3-k06a7ash1 commented
<img width="626" alt="スクリーンショット 2024-06-17 15 01 46" src="https://github.com/aws-samples/bedrock-claude-chat/assets/49641703/5acc55a1-7830-42cb-885d-9db2299658e0">
こんな感じでModal作成しました

2024-06-17 06:02 UTC, k70suK3-k06a7ash1 commented
@wadabee  @statefb 
こちらお手隙でご確認いただけますと幸いですmm

2024-06-17 06:03 UTC, k70suK3-k06a7ash1 commented
Lint修正

2024-06-17 12:19 UTC, wadabee requested changes
PRありがとうございます！
コメントをご確認くださいmm

2024-06-17 12:19 UTC, wadabee commented on frontend/src/pages/ChatPage.tsx
> +      <BottomHelper />
チャット入力欄の下部の余白が大きくなってしまっているので、元の余白のサイズに戻してください！
ヘルプは`fixed`とかでも良いのかなと思います！

2024-06-17 12:19 UTC, wadabee commented on frontend/src/pages/ChatPage.tsx
>        className="relative flex h-full flex-1 flex-col"
すみません。今回の修正とは関係ないですが、、
チャット欄のヘッダ(268行目)に`font-semibold`が設定されているので、削除をお願いしますmm

2024-06-17 12:19 UTC, wadabee commented on frontend/src/components/Textarea.tsx
> +      if (activeCodes['Escape'] && activeCodes['ShiftLeft']) {
特に左シフトに限定する理由はないと思うので、`ShiftRight`も追加をお願いします！

2024-06-17 12:19 UTC, wadabee commented on frontend/src/pages/ChatPage.tsx
> +        activeCodes['ShiftLeft'] &&
`Right`も同様に使えるように修正をお願いします！
また、Windowsの場合は、`Meta`ではなく`Control`です！

2024-06-17 12:19 UTC, wadabee commented on frontend/src/features/heler/components/BottomHelper.tsx
> +              <span className="text-sm">⌘</span>
Windowsの場合は、`Ctrl`としてください！

2024-06-17 12:19 UTC, wadabee commented on frontend/src/features/heler/components/BottomHelper.tsx
> +        <PiQuestionFill
アプリのデザイン思想として、「必ずクリックする必要のあるもの」「注意してクリックする必要があるもの」などを除き、outlinedなボタンにしています。
ヘルプはそれらに該当しないので、`fill`ではないアイコンをご利用くださいmm

送信ボタンがoutlinedなので、直したい気持ちになってきました。。
余裕があったら、 修正をお願いしますmm
（ボーダー無し、`bg-aws-sea-blue  hover:bg-aws-sea-blue-hover text-white`）

2024-06-18 04:54 UTC, k70suK3-k06a7ash1 commented
@wadabee 
レビューありがとうございます！！
修正します！

2024-06-18 04:56 UTC, k70suK3-k06a7ash1 commented
sample code
```typescript
var ua = window.navigator.userAgent.toLowerCase();

if(ua.indexOf("windows nt") !== -1) {
  console.log("「Microsoft Windows」をお使いですね!");
} else if(ua.indexOf("android") !== -1) {
  console.log("「Android」をお使いですね!");
} else if(ua.indexOf("iphone") !== -1 || ua.indexOf("ipad") !== -1) {
  console.log("「iOS」をお使いですね!");
} else if(ua.indexOf("mac os x") !== -1) {
  console.log("「macOS」をお使いですね!");
} else {
  console.log("何をお使いなのですか?");
}
```

2024-06-18 07:34 UTC, k70suK3-k06a7ash1 commented on frontend/src/features/heler/components/BottomHelper.tsx
> +        <PiQuestionFill
>送信ボタンがoutlinedなので、直したい気持ちになってきました。。
余裕があったら、 修正をお願いしますmm

こちら承知です！

2024-06-24 02:21 UTC, k70suK3-k06a7ash1 commented on frontend/src/features/heler/components/BottomHelper.tsx
> +        <PiQuestionFill
<img width="46" alt="スクリーンショット 2024-06-24 11 21 15" src="https://github.com/aws-samples/bedrock-claude-chat/assets/49641703/432eced8-d991-42d5-b0ac-7b1dcd79cf06">
<img width="88" alt="スクリーンショット 2024-06-24 11 21 26" src="https://github.com/aws-samples/bedrock-claude-chat/assets/49641703/fc806822-c41a-45ec-a8c6-879ecc864049">
上記のような感じで修正しました！
イメージ違ったらご指摘いただけると幸いですmm

2024-06-24 02:55 UTC, k70suK3-k06a7ash1 commented
Premise : macOS

|  | userAgent | userAgentData | 
| --- | --- | --- | 
|Safari | macOS | disabled api |
|Chrome | getOS => Android | NotWindows  as macOS |

2024-06-24 02:55 UTC, k70suK3-k06a7ash1 commented
```typescript
      window.navigator?.userAgentData
        ?.getHighEntropyValues(['platformVersion'])
        ?.then((ua) => {
          if (navigator.userAgentData.platform === 'Windows') {
            const majorPlatformVersion = parseInt(
              ua.platformVersion.split('.')[0]
            );
            if (majorPlatformVersion >= 13) {
              console.log('Windows 11 or later');
            } else if (majorPlatformVersion > 0) {
              console.log('Windows 10');
            } else {
              console.log('Before Windows 10');
            }
          } else {
            console.log('Not running on Windows');
          }
        });
```

2024-06-24 02:56 UTC, k70suK3-k06a7ash1 commented
```typescript
import Bowser from 'bowser';
...

const browser = Bowser.getParser(window.navigator.userAgent);
const os = browser.getOSName();
```

build-in

2024-06-24 05:13 UTC, k70suK3-k06a7ash1 commented
Windowsであるか否かの判定のみを行う
　＝＞!Bool でMacOSとして扱う

2024-06-25 01:19 UTC, wadabee commented on frontend/src/features/heler/components/BottomHelper.tsx
> +        <PiQuestionFill
ありがとうございます！助かります！
アイコンの存在感を出したいので、`Fiil`なアイコンでお願いしますmm

2024-06-25 02:46 UTC, k70suK3-k06a7ash1 commented on frontend/src/features/heler/components/BottomHelper.tsx
> +        <PiQuestionFill
すいません、認識誤ってましたmm

修正しました！

2024-06-25 04:33 UTC, k70suK3-k06a7ash1 commented
@statefb  @wadabee 
こちら修正とWindows端末での検証まで完了しました！

2024-06-25 05:49 UTC, statefb commented
ありがとうございます！
@wadabee LGTMでしたらマージお願いします！

2024-06-25 11:23 UTC, wadabee requested changes
ご対応ありがとうございます！
コメントのご確認お願いしますmm

2024-06-25 11:23 UTC, wadabee commented on frontend/src/features/heler/components/BottomHelper.tsx
> +  const isWindows = os === 'Windows';
ここ以外でも利用しているので、Hooks等を使って共通化していただけないでしょうか？

2024-06-25 11:23 UTC, wadabee commented on frontend/src/i18n/en/index.ts
> +        title: 'shortcut keys',
見出しは単語を大文字始まりにしているので、修正をお願いします！
`Shortcut Keys` のようなイメージです。

2024-06-25 11:23 UTC, wadabee commented on frontend/src/features/heler/components/BottomHelper.tsx
> +        <PiQuestionFill
すみません、わかりづらかったですmm
以下のような感じでお願いします！
<img width="138" alt="image" src="https://github.com/aws-samples/bedrock-claude-chat/assets/52243855/af999349-c1ca-4b68-8aff-3983ac1b5cac">

2024-06-27 05:00 UTC, k70suK3-k06a7ash1 commented on frontend/src/i18n/en/index.ts
> +        title: 'shortcut keys',
承知しました！

2024-07-02 02:27 UTC, wadabee commented on frontend/src/features/heler/components/BottomHelper.tsx
> +import { useState } from 'react';
すみません、見逃していました！
フォルダ名がtypoしています！（heler -> helper)

2024-07-02 03:02 UTC, k70suK3-k06a7ash1 commented on frontend/src/features/heler/components/BottomHelper.tsx
> +import { useState } from 'react';
指摘ありがとうございます！
失礼しましたmm

2024-07-02 05:32 UTC, wadabee approved these changes
LGTM !!
Thanks for your contribution!

2024-07-02 05:33 UTC, merged