add ErrorBoundary
aws-samples/bedrock-claude-chat pull request #372
Opened 2024-06-14 01:57 UTC by k70suK3-k06a7ash1

*Issue #, if available:*
#371
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-14 01:59 UTC, k70suK3-k06a7ash1 commented
@wadabee  @statefb 
予期せぬ不具合でAppがクラッシュした場合に、ユーザーが復元できるようError Boundaryを追加しました
ただ、UIどんな感じがいいか相談したいです！

現在はざっとcome backをonClickでwindow.location.href で"/"に遷移するようにしてます

<img width="686" alt="スクリーンショット 2024-06-14 10 57 53" src="https://github.com/aws-samples/bedrock-claude-chat/assets/49641703/902b0113-5ea7-400a-b0a5-c0227ab8e232">

2024-06-14 05:42 UTC, k70suK3-k06a7ash1 commented
<img width="1423" alt="スクリーンショット 2024-06-14 14 42 01" src="https://github.com/aws-samples/bedrock-claude-chat/assets/49641703/778194e1-60e9-4422-811e-62b846688f1e">

2024-06-14 09:00 UTC, wadabee requested changes

2024-06-14 09:00 UTC, wadabee commented on frontend/src/pages/ErrorFallback.tsx
> +    <div className="flex h-dvh flex-col items-center justify-center">
背景色は`aws-paper`でお願いします！

2024-06-14 09:00 UTC, wadabee commented on frontend/src/i18n/en/index.ts
> +        restore: 'Return to TOP page',
Return ではなく Go の方が適切かなと思いました！

2024-06-17 01:48 UTC, k70suK3-k06a7ash1 commented
@wadabee 
こちら修正しました！

2024-06-17 09:50 UTC, wadabee approved these changes
LGTM!!
ご対応ありがとうございました！

2024-06-17 09:51 UTC, merged