Feat/text file attach
aws-samples/bedrock-claude-chat pull request #412
Opened 2024-06-27 11:55 UTC by satoxiw

*Issue #, if available:*

*Description of changes:*
テキストファイルをリクエストに添付できる機能を追加しました。
MIME Typeで"text/*"となるものが対象ですが、環境によってはMIME Typeが正しく設定されないケースがあり、その場合は拡張子で判断するようになっています。対象となる拡張子は下記コード中に埋めていますが、これだと対象を追加しにくいかもしれないので、何か良い案があったらご指摘ください。
https://github.com/aws-samples/bedrock-claude-chat/compare/v1...satoxiw:bedrock-claude-chat:feat/text-file-attach?expand=1#diff-4f4332c2118277ddc90f75e9489ace8c6be3e9c60c88165e58063e8f25aa4734R37

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-28 01:01 UTC, Yukinobu-Mine commented
拡張子からの MIME type の推定は、このあたりのライブラリが使えそうです。
(既にフロントエンドの依存関係に含まれてるので、import するだけで使えると思います)
https://www.npmjs.com/package/mime

2024-07-01 00:15 UTC, statefb commented
Related issue: #198 
Partially solved

2024-07-01 00:44 UTC, statefb approved these changes
LGTM!

2024-07-01 01:03 UTC, statefb commented
`getAllTextExtensions`した結果をそのままhard codingしてしまった方が早い？
```js
["appcache","manifest","ics","ifb","coffee","litcoffee","css","csv","html","htm","shtml","jade","js","mjs","jsx","less","md","markdown","mml","mdx","n3","txt","text","conf","def","list","log","in","ini","dsc","rtx","rtf","sgml","sgm","shex","slim","slm","spdx","stylus","styl","tsv","t","tr","roff","man","me","ms","ttl","uri","uris","urls","vcard","curl","dcurl","mcurl","scurl","sub","ged","fly","flx","gv","3dml","spot","jad","wml","wmls","vtt","wgsl","s","asm","c","cc","cxx","cpp","h","hh","dic","htc","f","for","f77","f90","hbs","java","lua","mkd","nfo","opml","org","p","pas","pde","sass","scss","etx","sfv","ymp","uu","vcs","vcf","xml","yaml","yml"]
```

2024-07-01 01:40 UTC, statefb commented on backend/app/bedrock.py
> +                elif c.content_type == "textAttachment":
`textAttachment`を含む場合、下記のように展開されると思いますが、実際にtypeがtextのものが複数並ぶプロンプトの利用例はありますか？imageとtextが複数含まれる場合は[公式](https://docs.anthropic.com/ja/docs/vision#2)に推奨例として挙げられていますが、text複数の場合を見つけることができなかったので、もしご存知でしたら教えてくださいmm

```py
messages=[
    {"role": "user", "content": [{"type": "text", "body": "question_1"}]}, 
    {"role": "assistant", "content": [{"type": "text", "body": "answer_1"}]} 
    ...
    {"role": "assistant", "content": [{"type": "text", "body": "answer_n"}]},     
    # 質問文と実際のコードは（現在の実装では）順不同（？）
    # 
     {"role": "user", "content": "content": [{"type": "text", "body": "explain the code."}]},     
     {"role": "user", "content": "content": [{"type": "text", "body": "<attachment: ...略..."}]},     
]
```

2024-07-01 05:21 UTC, Yukinobu-Mine commented on backend/app/bedrock.py
> +                elif c.content_type == "textAttachment":
> wild cardで抽出できなかったのですべて指定が必要そうですね
について、「wild cardで抽出できなかった」というのは、何をしようとされた感じでしょうか?
私が mime ライブラリでの実装を想定していたのは、以下のような判定ロジックです。
1. `const mimeType = mime.getType(file.name)` で、拡張子に対応する MIME Type を取得する
2. mimeType が `text/` で始まっていればテキストと判定する (`application/json` とか `application/javascript` といった例外があれば、それもテキストと判定する)

2024-07-01 08:57 UTC, satoxiw commented
> 拡張子からの MIME type の推定は、このあたりのライブラリが使えそうです。 (既にフロントエンドの依存関係に含まれてるので、import するだけで使えると思います) https://www.npmjs.com/package/mime
> 
> このライブラリが内部的に参照してるマッピング情報はこちらのようです。 https://github.com/jshttp/mime-db/blob/master/db.json

情報ありがとうございます。一般的にtext/*のMIME Typeになるファイルに関してはこれでなんとかなりそうです。
一方で、例外のものをどうするかという検討も必要ですが、例外のMIME Typeを列挙すれば良いかなと思ったのですが、それでも例外は一部ありそうでして、例えば、TypeScriptの拡張子`ts`は一般的にはMPEG2TSのファイルの拡張子という扱いとなっているようで、本ライブラリで判定すると`video/mp2t`となります。これを許可しておくのはちょっと違うなとなりそうだったり、jsx要素を含む`tsx`ファイルに至ってはMIME Typeが判定できません。

ですので、text形式としてMIME Typeが判明しているものは、mimeを使って判定し、それ以外の例外については、ハードコーディングされた拡張子一覧で判断が現実的かなと思っていますがいかがでしょうか？

2024-07-01 09:00 UTC, statefb commented on backend/app/bedrock.py
> +                elif c.content_type == "textAttachment":
ありがとうございます。私の想定は`mime.getAllExtension('text/*'); `を実行後、実際の拡張子がそれに含まれるか判定する方法を想定していました。~~仰る通りの方法が良さそうですね！~~ 実際に試すとsatoxiwさんの[コメント](https://github.com/aws-samples/bedrock-claude-chat/pull/412#issuecomment-2199605252)にある通り、tsの場合はvideo/mp2となってしまいますね。。

2024-07-01 10:16 UTC, wadabee requested changes
ご確認をお願いしますmm

2024-07-01 10:16 UTC, wadabee commented on frontend/src/index.css
> +}
tailwind cssを使ってスタイリングをお願いします

2024-07-01 10:16 UTC, wadabee commented on frontend/src/hooks/useChat.ts
> +        console.log(input);
デバッグログが残っています

2024-07-01 10:16 UTC, wadabee commented on frontend/src/hooks/useChat.ts
> +  extracted_content: string;
JS界隈では、変数名（フィールド名も含む）は lower camel case での命名が文化なので、修正をお願いします！

2024-07-01 10:16 UTC, wadabee commented on frontend/src/components/ChatMessageMarkdown.tsx
> +        },
このファイルの修正は必要でしょうか？
（消し忘れ？）

2024-07-01 10:16 UTC, wadabee commented on frontend/src/components/ChatMessage.tsx
> +                      </div>
テキストファイルの表示部分については、`UploadedFileText.tsx`というコンポーネントを作って、以下のレイアウトでお願いします！
InputChatContent.tsxのコードとの共通化もお願いします（truncateFileNameなども含めて共通化）

```ts
                        <div
                          key={idx}
                          className="relative mx-2 flex cursor-pointer flex-col items-center hover:brightness-75"
                          onClick={() =>
                            handleFileClick(content.fileName, content.body)
                          }>
                          <div className="flex w-full ">
                            <div className="w-full rounded-tl-lg border-l border-t border-gray bg-aws-paper"></div>
                            <svg
                              viewBox="0 0 16 16"
                              xmlns="http://www.w3.org/2000/svg"
                              className="block h-4 w-4 shrink-0 drop-shadow">
                              <path
                                d="M0 0L16 16H0V0Z"
                                className="fill-aws-paper stroke-gray"
                                stroke-width="0.5"></path>
                            </svg>
                          </div>
                          <div className="rounded-b-lg border-x border-b border-gray bg-aws-paper p-2 ">
                            <div className="w-16 text-xs font-bold text-dark-gray">
                              {truncateFileName(content.fileName)}
                            </div>
                          </div>
                        </div>
```

2024-07-01 10:16 UTC, wadabee commented on frontend/src/components/ChatMessage.tsx
> +                </div>
`ModalDialog`にtitleの属性があるので、そちらで件名の設定をお願いします！
また、ファイル全体をコピーして別のチャットに貼り付けるユースケースはほぼ無いと思うので、コピーボタンはなくてもいいかなと思いました！（もし、想定していたユースケースがありましたら、遠慮なく教えていただけましたら）

2024-07-01 10:16 UTC, wadabee commented on frontend/src/components/ChatMessage.tsx
> +                <div className="p-4 overflow-auto">
余白は`px-4`でお願いします！

2024-07-01 10:16 UTC, wadabee commented on frontend/src/components/ChatMessage.tsx
> +                  <pre className="whitespace-pre-wrap break-all">{fileContent}</pre>
改行があった方がわかりやすいと思うので、以下のように修正をお願いします！
```ts
                {fileContent.split('\n').map((c, idxBody) => (
                        <div key={idxBody}>{c}</div>
                      ))}
```

2024-07-02 02:26 UTC, satoxiw commented on frontend/src/hooks/useChat.ts
> +        console.log(input);
失礼しました。削除します。

2024-07-02 02:32 UTC, satoxiw commented on frontend/src/hooks/useChat.ts
> +  extracted_content: string;
修正します。加えて、`file_size`も現在使用していないので削除します。

2024-07-02 02:34 UTC, satoxiw commented on frontend/src/components/ChatMessageMarkdown.tsx
> +        },
これは、別件で入れた修正が混じっていました。`SyntaxHighlighter`のスタイリング含めて修正してしまっているので戻します。

2024-07-02 02:40 UTC, satoxiw commented on frontend/src/components/ChatMessage.tsx
> +                </div>
`title`の利用了解しました。
>また、ファイル全体をコピーして別のチャットに貼り付けるユースケースはほぼ無いと思うので、コピーボタンはなくてもいいかなと思いました！（もし、想定していたユースケースがありましたら、遠慮なく教えていただけましたら）
そうですね。どんなファイルだったかなとコピーしたいこともあるかなと思ってつけたのですが、いらなそうですね。削除したいと思います。

2024-07-02 02:41 UTC, satoxiw commented on frontend/src/components/ChatMessage.tsx
> +                <div className="p-4 overflow-auto">
修正します。

2024-07-02 02:43 UTC, satoxiw commented on frontend/src/components/ChatMessage.tsx
> +                  <pre className="whitespace-pre-wrap break-all">{fileContent}</pre>
こちら、`pre`タグ内なので改行そのままで出ると思いますが、`pre`タグに入れない方が良いでしょうか？

2024-07-02 02:44 UTC, satoxiw commented on frontend/src/index.css
> +}
こちら、↓の不要な`SyntaxHighlighter `の修正の際に入れていたもので、不要なため削除します。

2024-07-02 07:42 UTC, satoxiw commented on frontend/src/hooks/useChat.ts
> +        draft.content[textIndex].body = props.content;
`ChatMessage.tsx`の処理と被って冗長な面もありますが、こちらでも更新対象が`content[0]`と固定だったため修正しています

2024-07-02 07:42 UTC, satoxiw commented on frontend/src/components/ChatMessage.tsx
> +                setChangedContent(chatContent.content[firstTextContent].body);
再生成時の処理対象が`content[0].body`と固定だったので、対象の`text`の変更を行うように修正しています

2024-07-02 07:43 UTC, satoxiw commented on frontend/src/components/InputChatContent.tsx
> +// To change the supported text format files, change the extension list below.
すでにディスカッションしている通りですが、MIMEベースでドラック可能ファイルを特定する方法だと、例外対応であったり、そもそもMIMEで判断できないケースもあるため、許可するファイルを固定で定義しました。一旦許可するファイル一覧は、Claude.aiが許可しているテキスト形式のファイルを対象としました。

2024-07-02 07:58 UTC, satoxiw commented on frontend/src/components/InputChatContent.tsx
> +];
すでにディスカッションしている通りですが、MIMEベースでドラック可能ファイルを特定する方法だと、例外対応であったり、そもそもMIMEで判断できないケースもあるため、許可するファイルを固定で定義しました。一旦許可するファイル一覧は、Claude.aiが許可しているテキスト形式のファイルを対象としました。

2024-07-02 08:01 UTC, satoxiw commented on frontend/src/components/InputChatContent.tsx
>          </Alert>
添付不可のファイルがドラッグされた場合のアラート入れてみましたが、どんな感じが良いか悩んだ上Transition + Alertとしてみました。こうした方が良いなどあればコメントいただければと思います。

2024-07-02 08:44 UTC, satoxiw commented on frontend/src/components/ChatMessage.tsx
> +                      </div>
こちらご指摘いただいた形で、`UploadedFileText.tsx`を作ってChatMessageおよびInputChatContentで流用する形に修正しました

2024-07-02 08:45 UTC, satoxiw commented on frontend/src/components/InputChatContent.tsx
>          </Alert>
こちら別途お教えいただた通り、`useSnackbar `を使う形に修正しました

2024-07-03 00:43 UTC, wadabee commented on frontend/src/components/ChatMessage.tsx
> +                  <pre className="whitespace-pre-wrap break-all">{fileContent}</pre>
失礼しましたmm
改行含めて正しく表示されていたので、問題ありません！

2024-07-03 01:43 UTC, wadabee approved these changes
LGTM!!
ご対応ありがとうございました！

2024-07-03 01:45 UTC, merged