Feature/atom stories
aws-samples/bedrock-claude-chat pull request #415
Opened 2024-07-01 14:37 UTC by k70suK3-k06a7ash1

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-01 14:38 UTC, k70suK3-k06a7ash1 commented
先行PR：https://github.com/aws-samples/bedrock-claude-chat/pull/378

2024-07-02 03:02 UTC, k70suK3-k06a7ash1 commented
recreate file changed

2024-07-02 17:49 UTC, k70suK3-k06a7ash1 commented
Atomレベルのコンポーネント、一旦一通りカタログ化できたかと思いますmm

2024-07-02 17:49 UTC, k70suK3-k06a7ash1 commented on frontend/src/constants/index.ts
> +export const SyncStatus = {
オブジェクトリテラルでEnum化しました

2024-07-02 18:08 UTC, k70suK3-k06a7ash1 commented
TooltipDirectionのLeftが使われていないようなので削除しても良いかもしれません

2024-07-02 18:14 UTC, k70suK3-k06a7ash1 commented
細かな修正も合わせてコミットしておりますmm

2024-07-10 05:40 UTC, wadabee requested changes
ご対応ありがとうございます！！
確認が遅くなりまして、申し訳ありませんmm

コンポーネントの俯瞰性が上がって非常に良きです！
軽微なコメントがあるので、ご確認くださいmm

2024-07-10 05:40 UTC, wadabee commented on frontend/src/pages/ChatPage.tsx
> +                          onClickBotEdit(bot.id);
ここのdiffはどういった意図がありますか？（Formatterの設定？）
非常に短いコードなので、変更前の方が可読性が高いように感じます。

2024-07-10 05:40 UTC, wadabee commented on frontend/src/pages/ChatPage.tsx
> +                          onClickCopyUrl(bot.id);
L315と同様

2024-07-10 05:40 UTC, wadabee commented on frontend/src/hooks/useScroll.ts
> +    if (!elem) return;
個人的な好みの問題もあるのですが、ifに限らず`{}`があった方が可読性が高いように感じるので、元のコードに戻していただければと思いますmm
ESLintに以下のルールの追加をお願いします！
```
    curly: ['error', 'all'],
```

2024-07-10 06:13 UTC, k70suK3-k06a7ash1 commented on frontend/src/pages/ChatPage.tsx
> +                          onClickBotEdit(bot.id);
early return することでネストを無くそうと思い変更しました！

以下いただいたコメントと同じく、{}記載する方針と理解しましたので、修正いたします！

2024-07-13 14:44 UTC, k70suK3-k06a7ash1 commented
@wadabee 
こちら修正いたしました！

2024-07-13 14:44 UTC, k70suK3-k06a7ash1 commented on frontend/.eslintrc.cjs
> +    curly: ['error', 'all'],
こちら、追加しております！

2024-07-13 14:50 UTC, k70suK3-k06a7ash1 commented on frontend/src/pages/ChatPage.tsx
> +      if (hasKeyDownCommand) {
真偽判定を反転させてます！

2024-07-16 12:34 UTC, wadabee approved these changes
LGTM
ご対応ありがとうございました！

2024-07-16 12:34 UTC, merged