Fix 196
aws-samples/bedrock-claude-chat pull request #417
Opened 2024-07-01 15:57 UTC by k70suK3-k06a7ash1

*Issue #, if available:*
#196 
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-01 17:54 UTC, k70suK3-k06a7ash1 commented on frontend/src/main.tsx
> +// unsafe
@wadabee  @statefb 
pathを型定義で縛りたく、readonlyで厳密にしたところ、ReactRouter側で参照できなくなってしまったので、型外して再度キャストしてます
よくない実装ではあるので、この点相談させていただきたいですmm

2024-07-02 01:58 UTC, k70suK3-k06a7ash1 commented on frontend/src/components/AppContent.tsx
> +                {isConversationOrNewChat
今回の根本的な修正箇所はこちらとなりますmm

2024-07-10 08:24 UTC, wadabee requested changes
ご対応ありがとうございます！
確認が遅くなって、申し訳ございませんmm
コメントご確認ください！

2024-07-10 08:24 UTC, wadabee commented on frontend/src/main.tsx
> +// unsafe
`routes.tsx` で export している `routes` を `RouteObject[]`として定義すれば、こちらでType Assertionしなくても大丈夫ではないでしょうか？
できれば、特殊な実装はモジュール内に閉じ込めておきたいです！（理想は根本原因となっているモジュール内）

2024-07-10 08:24 UTC, wadabee commented on frontend/src/routes.tsx
> +    { path: '/admin/api-management', label: t('button.apiManagement') },
元の実装が悪いのですが、画面名は独立したキーで管理したいです！
（画面名とボタン名は役割が異なるため）

2024-07-10 08:24 UTC, wadabee commented on frontend/src/components/AppContent.tsx
> +  const isConversationOrNewChat = !routes?.length;
全体的にメモ化をお願いします！

2024-07-10 08:24 UTC, wadabee commented on frontend/src/components/AppContent.tsx
> +  const isConversationOrNewChat = !routes?.length;
この部分がリーダブルになっていない印象を受けました。
変数名に、route, path, patternが入り混じっているのが、わかりづらい要因かと思います。
（もし、意図的に単語を使い分けているのであれば、お知らせください）
以下の修正案はただの一案なので、気軽にご意見ください！

- `conversationOrNewChatRoutes` => `conversationRoutes`
- `extractPathPattern` => `notConversationRoutes`
- `pathPattern`, `routes` 
  - これらがわかりづらくしている原因かもです
  - `pathPattern`は、locationから取ってきてもいいのではないでしょうか？
  - `routes`に格納せずに、`isConversationOrNewChat`に代入するロジックでワンライナーでかけないでしょうか？

2024-07-10 09:12 UTC, k70suK3-k06a7ash1 commented on frontend/src/main.tsx
> +// unsafe
```typescript
  const conversationOrNewChatRoutes: { path: (typeof allPaths)[number] }[] = [
    { path: '/:conversationId' },
    { path: '/bot/:botId' },
    { path: '/' },
    { path: '*' },
  ];
```
こちらのtypeof allPathsが全てstringになってしまうので、readonlyにして型定義を厳密にしたかったというモチベーションでしたmm

2024-07-13 14:57 UTC, k70suK3-k06a7ash1 commented on frontend/src/main.tsx
> +// unsafe
rootChildrenをas const していない場合とした場合の型定義の差分をスクショで共有させていただきますmm
<img width="196" alt="スクリーンショット 2024-07-13 23 55 02" src="https://github.com/user-attachments/assets/a4a40c58-f2eb-4590-bbb7-9a261feb988f">

<img width="652" alt="スクリーンショット 2024-07-13 23 55 13" src="https://github.com/user-attachments/assets/aa78c5a7-02f2-4869-8ba3-c8707777ee6e">


>特殊な実装はモジュール内に閉じ込めておきたいです！
こちらご指摘ありがとうございます！おっしゃる通りだと思いまして、routes.tsファイルからrouterをexportするように移動いたしましたmm

2024-07-13 15:13 UTC, k70suK3-k06a7ash1 commented on frontend/src/routes.tsx
> +    { path: '/admin/api-management', label: t('button.apiManagement') },
こちら修正しました！
ご指摘ありがとうございます！

2024-07-13 15:32 UTC, k70suK3-k06a7ash1 commented on frontend/src/components/AppContent.tsx
> +  const isConversationOrNewChat = !routes?.length;
ありがとうございます！
こちらlocation.pathnameがstring型になっているために冗長な実装となってしまいましたmm

確かに可読性下がっていたのでcustomHooksで分離しましたmm

2024-07-16 14:19 UTC, wadabee approved these changes
LGTM!
ご対応ありがとうございます！

コンフリクトの修正をお願いしますmm
`v1` 側優先でお願いしますmm

2024-07-16 14:40 UTC, k70suK3-k06a7ash1 commented
ご確認いただきありがとうございます！

2024-07-17 08:55 UTC, merged