Added option to choose streaming or not
aws-samples/bedrock-claude-chat pull request #55
Opened 2023-10-13 05:43 UTC by wildgeece96

*Issue #, if available:*

*Description of changes:*

- Added environment value to switch streaming or not when post message to Bedrock.
- Fixed typo of README.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-13 08:27 UTC, wadabee requested changes
PRありがとうございます！
READMEのどこかに、「バックエンドをローカルで動かす場合は、Streamingを利用しない」「AWSで動かす場合は、Streaming推奨」というような記載をお願いしますmm

2023-10-13 08:27 UTC, wadabee commented on docs/README_ja.md
> +cli および CDK を利用されている場合、`cdk destroy`を実行してください。そうでない場合は[CloudFormation](https://console.aws.amazon.com/cloudformation/home)へアクセスし、手動で`BedrockChatStack`を削除してください。
typoの修正ありがとうございます！

2023-10-13 08:27 UTC, wadabee commented on frontend/src/hooks/useChat.ts
> +    if (USE_STREAMING) {
Streamingとそれ以外で後処理の内容は一緒だと思うので、共通化したいです。
一例として以下のような書き方もあるかなーと思います（書き方はお任せします）

```
    const postPromise: Promise<void> = new Promise((resolve) => {
      if (USE_STREAMING) {
        postStreaming(input, (c: string) => {
          editLastMessage(conversationId ?? '', c);
        }).then(() => {
          resolve();
        });
      } else {
        conversationApi.postMessage(input).then((res) => {
          editLastMessage(conversationId ?? '', res.data.message.content.body);
          resolve();
        });
      }
    });
    
    postPromise.then(()=>{
    // 共通処理
    })
```

2023-10-16 02:39 UTC, wildgeece96 commented on frontend/src/hooks/useChat.ts
> +    if (USE_STREAMING) {
共通化したかったけれども上手いやり方が思いついていなかったところだったのでとても助かります。

修正加えます！

2023-10-16 06:24 UTC, wadabee approved these changes
LGTM!!
コントリビュートありがとうございます！

2023-10-16 06:27 UTC, merged