feat: control LLM model selection through configuration
aws-samples/bedrock-claude-chat pull request #607
Opened 2024-11-22 09:00 UTC by fsatsuki

*Issue #, if available:*
#592 

*Description of changes:*
When publishing chatbots, you may want to limit the models that can be used, such as when you want to restrict the use of expensive models. 
This update adds the ability to limit which models can be used per custom chatbot.
All models can be used with regular chatbots.

Add ModelActivate to DynamoDB and set true/false whether the model can be used. The chatbot can only select models that are set to true.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-11-26 03:36 UTC, statefb commented on backend/app/repositories/models/custom_bot.py
> +class ModelActivateModel(BaseModel):
モデルは今後も増える可能性が非常に高いので、なるべくメンテナンスの負荷を小さくしたいと考えています。モデル候補はapp.routes.schemas.conversation.pyの`type_model_name`に既に宣言されているので、二重メンテになります。たとえば下記のような方針で、動的に対処することを検討くださいmm

2024-11-26 03:36 UTC, statefb commented on backend/app/repositories/models/custom_bot.py
> +class ModelActivateModel(BaseModel):
- モデル定義を一元管理
```py
from typing import List

MODEL_NAMES: List[str] = [
    "claude-instant-v1",
    "claude-v2",
    "claude-v3-sonnet",
    "claude-v3.5-sonnet",
    "claude-v3.5-sonnet-v2",
    "claude-v3.5-haiku",
    "claude-v3-haiku",
    "claude-v3-opus",
    "mistral-7b-instruct",
    "mixtral-8x7b-instruct",
    "mistral-large",
]
```

`type_model_name`を動的に生成
```py
from typing import Literal

type_model_name = Literal[tuple(MODEL_NAMES)]
```

ModelActivateModel を動的に生成
```py
from pydantic import BaseModel
from typing import Optional

def create_model_activate_model(model_names: List[str]) -> BaseModel:
    fields = {
        name.replace("-", "_").replace(".", "_"): (Optional[bool], None)
        for name in model_names
    }
    return type("ModelActivateModel", (BaseModel,), fields)

ModelActivateModel = create_model_activate_model(MODEL_NAMES)

```

上記はLLMで生成したものなので動作するかわかりませんが、参考までお願いします！

2024-11-26 03:36 UTC, statefb commented on backend/app/repositories/models/custom_bot.py
> +class ModelActivateModel(BaseModel):
もう一つお願いですが、`ModelActivateModel`が名前としてややこしい（仕方ないですが）ので、用途のコメント書いていただけると助かります！

2024-11-26 03:36 UTC, statefb commented on backend/app/repositories/models/custom_bot.py
> +    model_activate: ModelActivateModel | None
条件分岐を減らすため、ModelはNone非許容にしてください！（KB系はKBの仕様で仕方なくNoneにしていた背景があります）.   
schemaのinput / modify_inputはnone許容で良いと思いますが、DDBに永続化する段階でデフォルト値で埋める処理が良いかと思います (outputはNone許容しない。FEはすべて埋まっている前提で処理すればOK)。
conversation_quick_starterが参考になると思います

2024-11-26 03:36 UTC, statefb commented on backend/pyproject.toml
> +moto = "^5.0.21"
不要ですか？

2024-11-26 03:36 UTC, statefb commented on backend/app/usecases/bot.py
> +        update_bot_model_activate(user_id, bot)
aliasのケアありがとうございます（結構忘れやすいので、さすがです）！   
ここでupdateするのではなく、usecases.bot.pyのfetch_allbots_by_user_id側で一覧取得する際に更新するよう実装してください！

```py
if is_original_available and (
                bot.title != item["Title"]
                or bot.description != item["Description"]
                or bot.sync_status != item["SyncStatus"]
                or bot.has_knowledge() != item["HasKnowledge"]
                or bot.conversation_quick_starters
                != [
                    ConversationQuickStarter(**starter)
                    for starter in item.get("ConversationQuickStarters", [])
                ]
                or...   # ここに条件が追加されるイメージ
            ):
                # Update alias to the latest original bot
                store_alias(
                    user_id,
                    BotAliasModel(
                        id=decompose_bot_alias_id(item["SK"]),
                        # Update title and description
                        title=bot.title,
                        description=bot.description,
                        original_bot_id=item["OriginalBotId"],
                        create_time=float(item["CreateTime"]),
                        last_used_time=float(item["LastBotUsed"]),
                        is_pinned=item["IsPinned"],
                        sync_status=bot.sync_status,
                        has_knowledge=bot.has_knowledge(),
                        has_agent=bot.is_agent_enabled(),
                        conversation_quick_starters=bot.conversation_quick_starters,
                        model_activate=bot.model_activate,
                    ),
                )
```

これでrepoの`update_bot_model_activate`も不要になり、シンプルになります

2024-11-26 03:36 UTC, statefb commented on frontend/src/@types/bot.d.ts
> +export type ModelActivate = {
こちらもBE同様、メンテ負荷を減らすため、conversation.d.tsのModel定義から動的に生成する方法でお願いします！

2024-11-26 03:39 UTC, statefb commented on backend/app/routes/schemas/bot.py
> +    claude3_sonnet_v1: bool | None
これはNone非許容で良いかと思いました (ModelActivateInput自体がNone許容なので)

2024-11-26 03:39 UTC, statefb commented on backend/app/routes/schemas/bot.py
> +    claude3_sonnet_v1: bool | None
同上

2024-11-26 03:40 UTC, statefb commented on backend/app/repositories/models/custom_bot.py
> +    claude3_haiku_v1: Optional[bool] = None
こちらもNone非許容で良いと思います

2024-11-26 03:42 UTC, statefb commented on backend/app/repositories/custom_bot.py
> +            ModelActivateModel(**item["ModelActivate"])
こちらも（後方互換性を保つため）ModelActivateがNoneの場合はNoneを返すのではなく、デフォルト値を返すようにしてください！

2024-12-05 07:06 UTC, fsatsuki commented on backend/app/repositories/models/custom_bot.py
> +class ModelActivateModel(BaseModel):
モデルが増えても追加しやすい実装にしました。

2024-12-05 07:06 UTC, fsatsuki commented on backend/app/repositories/models/custom_bot.py
> +    model_activate: ModelActivateModel | None
対応しました。

2024-12-05 07:06 UTC, fsatsuki commented on backend/pyproject.toml
> +moto = "^5.0.21"
削除します。

2024-12-05 07:06 UTC, fsatsuki commented on backend/app/usecases/bot.py
> +        update_bot_model_activate(user_id, bot)
対応しました。

2024-12-05 07:06 UTC, fsatsuki commented on frontend/src/@types/bot.d.ts
> +export type ModelActivate = {
対応しました。

2024-12-05 07:06 UTC, fsatsuki commented on backend/app/routes/schemas/bot.py
> +    claude3_sonnet_v1: bool | None
対応しました。

2024-12-05 07:06 UTC, fsatsuki commented on backend/app/routes/schemas/bot.py
> +    claude3_sonnet_v1: bool | None
対応しました。

2024-12-05 07:06 UTC, fsatsuki commented on backend/app/repositories/models/custom_bot.py
> +    claude3_haiku_v1: Optional[bool] = None
対応しました。

2024-12-05 07:06 UTC, fsatsuki commented on backend/app/repositories/custom_bot.py
> +            ModelActivateModel(**item["ModelActivate"])
対応しました。

2024-12-05 08:48 UTC, statefb commented on backend/app/repositories/custom_bot.py
> +        model_activate=ModelActivateModel.model_validate(item.get("ModelActivate")),
ここでは　model_validateしているのに、別の箇所では
```py
model_activate=ModelActivateOutput(**dict(bot.model_activate)),
```
と統一されていないのには何か理由がありますか？  

また既存のボットではitem.getした結果がNoneになると思いますが、現状ではエラーになりませんかね？  item.get("ModelActivate", {})とすべきでしょうか？

2024-12-05 08:48 UTC, statefb commented on backend/app/repositories/custom_bot.py
> +    if model_activate:
Noneではないのでupdate_expression / expression_attributes_valuesを宣言しているところへ記述ください！

2024-12-05 08:48 UTC, statefb commented on backend/app/repositories/models/custom_bot.py
> +class DynamicBaseModel(BaseModel):
bot専用ではないので　common.py側へ移植ください！

2024-12-05 08:48 UTC, statefb commented on backend/app/routes/bot.py
> +        model_activate=ModelActivateOutput(**dict(bot.model_activate)),
model_validate?

2024-12-05 08:48 UTC, statefb commented on backend/app/repositories/models/custom_bot.py
> +        name.replace("-", "_").replace(".", "_"): (bool, False) for name in model_names
デフォルト値がFalseなので、このPR前に作成したボットだと全てのボットが利用不可能になってしまいますかね？（違ったらすみません）

2024-12-05 11:49 UTC, fsatsuki commented on backend/app/repositories/custom_bot.py
> +        model_activate=ModelActivateModel.model_validate(item.get("ModelActivate")),
明確な理由はなかったので、 `ModelActivateModel.model_validate` に統一します。

2024-12-05 11:51 UTC, fsatsuki commented on backend/app/repositories/custom_bot.py
> +    if model_activate:
修正します

2024-12-05 12:21 UTC, fsatsuki commented on backend/app/repositories/models/custom_bot.py
> +class DynamicBaseModel(BaseModel):
修正しました

2024-12-05 12:21 UTC, fsatsuki commented on backend/app/routes/bot.py
> +        model_activate=ModelActivateOutput(**dict(bot.model_activate)),
修正しました

2024-12-05 12:21 UTC, fsatsuki commented on backend/app/repositories/models/custom_bot.py
> +        name.replace("-", "_").replace(".", "_"): (bool, False) for name in model_names
デフォルトTrueの誤りです。修正しました。

2024-12-06 04:09 UTC, statefb commented on frontend/src/constants/index.ts
> +export const MODEL_KEYS: Model[] = [
conversation.d.tsのModelから生成検討してください！

2024-12-06 04:09 UTC, statefb commented on frontend/src/features/knowledgeBase/pages/BotKbEditPage.tsx
activeModelsOptions、動的に生成することを検討ください！

2024-12-06 06:50 UTC, fsatsuki commented on frontend/src/constants/index.ts
> +export const MODEL_KEYS: Model[] = [
typescriptの言語の問題で、typeの中身を変数の値として使うことは実装不可能でした。

2024-12-06 07:33 UTC, fsatsuki commented on frontend/src/features/knowledgeBase/pages/BotKbEditPage.tsx
対応しました。
動的に生成するためにi18nの一部のkeyを変更しています。また、使っていないClaudeの古いモデルはi18nから削除しました。

2024-12-06 11:26 UTC, statefb commented on frontend/src/constants/index.ts
> +export const MODEL_KEYS: Model[] = [
[commit](https://github.com/aws-samples/bedrock-claude-chat/pull/607/commits/a0b86ae1636f7b4741b1f4386cc171268f95b0ba)で実装

2024-12-06 11:28 UTC, statefb commented on frontend/src/@types/conversation.ts
動的に生成するためd.ts -> .tsに変更

2024-12-06 11:41 UTC, statefb approved these changes
lgtm

2024-12-06 11:48 UTC, statefb commented
@wadabee FE側ご確認いただけると助かります！

2024-12-09 02:14 UTC, wadabee requested changes

2024-12-09 02:14 UTC, wadabee commented on frontend/src/i18n/ja/index.ts
> +        title: 'モデル設定',
こちらは、「利用可能なモデル設定」のほうが良いかなと思いました。
「モデル設定」だと、モデル自体の設定項目な印象を持ちました。

2024-12-09 02:14 UTC, wadabee commented on frontend/src/features/knowledgeBase/pages/BotKbEditPage.tsx
> +                        <span>{label}</span>
ここにもモデルの説明があったほうが良いかなと思いました！

L2398を` className="flex items-start"`に変更して、
L2407を以下のように修正すると良い感じになると思います。
```tsx
<div>
  <div>{label}</div>
  <div className="text-sm text-dark-gray">{description}</div>
</div>
```

2024-12-09 02:14 UTC, wadabee commented on frontend/src/@types/conversation.ts
`@types`に`.ts`があると秩序が乱れそう（ロジックが埋め込み可能になる）なので、`MODEL_KEYS`を`constants/index.ts`に移動できないでしょうか？
また、定数名も`AVAILABLE_MODEL_KEYS`のような感じで、利用可能なモデル一覧という名前の方が良いと思います。

2024-12-09 02:14 UTC, wadabee commented on frontend/src/hooks/useModel.ts
> +    processedActiveModels,
ここにたくさんdependenciesが入っていますが、`botId`だけだと何かカバーできない部分があったりしますかね？

2024-12-10 04:25 UTC, fsatsuki commented on frontend/src/i18n/ja/index.ts
> +        title: 'モデル設定',
修正しました。

2024-12-10 04:58 UTC, fsatsuki commented on frontend/src/features/knowledgeBase/pages/BotKbEditPage.tsx
> +                        <span>{label}</span>
修正しました。

2024-12-10 04:58 UTC, fsatsuki commented on frontend/src/hooks/useModel.ts
> +    processedActiveModels,
修正しました。

2024-12-10 05:51 UTC, wadabee commented on frontend/src/features/knowledgeBase/pages/BotKbEditPage.tsx
> +                        <span>{label}</span>
`activeModelsOptions`こちらに`description`の追加をお願いしますmm

2024-12-10 05:52 UTC, wadabee commented on frontend/src/@types/conversation.ts
@fsatsuki 
拡張子を`d.ts`に戻していただけますとmm

2024-12-10 09:22 UTC, fsatsuki commented on frontend/src/hooks/useModel.ts
> +    processedActiveModels,
botidだけにしました。

2024-12-12 01:38 UTC, wadabee approved these changes
LGTM!

2024-12-12 01:38 UTC, merged